GET http://localhost:5000

###
GET http://localhost:5000/abc

###

POST http://localhost:5000/user/register

###

POST http://localhost:5000/user/refresh-token

###

POST http://localhost:5000/user/login

###

POST http://localhost:5000/user/logout