GET http://localhost:5000

###
GET http://localhost:5000/abc

###
POST  http://localhost:5000/user/register
Content-Type: application/json

{
    "email": "khainp2@gmail.com",
    "password": "abc1!231"
}

###
POST  http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "khainp1@gmail.com",
    "password": "abc1!231"
}

###
GET http://localhost:5000/user/getlists
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDEyNjYwNDMsImV4cCI6MTY0MTI2NjEwM30.0k6SReyYDm2zhBbZ6Gzode909Wm5mWyHVfBTiHU9nAY

###
POST http://localhost:5000/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNhN2RmYzBiYzU1Y2EyZWM1ZTk3NTIiLCJpYXQiOjE2NDEyNjIwMDksImV4cCI6MTY0MTM0ODQwOX0.kNJFFkCoRj6VaHgq6QwmQjuBbgfjlMxVyEyTjd28x_M"
}