GET http://localhost:5000

###
GET http://localhost:5000/abc

###
POST  http://localhost:5000/user/register
Content-Type: application/json

{
    "email": "khainp2@gmail.com",
    "password": "abc1!231"
}

###
POST  http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "khainp1@gmail.com",
    "password": "abc1!231"
}

###
GET http://localhost:5000/user/getlists
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDEzNTA2MDcsImV4cCI6MTY0MTM1MDY2N30.SattkMXIFFEc8spPnNF7lkDusGcWJFUHxI6WkiuutRs

###
POST http://localhost:5000/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNhN2RmYzBiYzU1Y2EyZWM1ZTk3NTIiLCJpYXQiOjE2NDEzNTM5MDgsImV4cCI6MTY0MTQ0MDMwOH0.S_SKW_9mEykGglHN7kxfh2oyxWBDX0aJaOtPJq3YJgo"
}

###
DELETE http://localhost:5000/user/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNhN2RmYzBiYzU1Y2EyZWM1ZTk3NTIiLCJpYXQiOjE2NDEzNTUzMjQsImV4cCI6MTY0MTQ0MTcyNH0.BVhsFRn3s1v-6na2c0RBkubdpwnhpWlXLvacluNFu1M"
}